mentionnames = ["rice", "ricecooker", "@ricecooker", "@ricecookerisnotabot"]
sadgreet = ["spill", "trip", "eat", "eat you", "bite", "bite you","tips", "tips over"]
killgreet = ["unplug", "unplug you", "kill", "kill you", "rip", "destroy", "hate", "hate you"]
randomgreet = ["Hello", "Hi", "Greetings", "Good day", "How are ya?", "Yes", "No", "What's up?"]
assumptgreet = ["akala ko si rice", "akala ko si ricecooker", "akala ko si @ricecooker", "kala ko si rice", "kala ko si @ricecooker", "kala ko si ricecooker", "ikaw ba yan rice", "kaw ba yan rice", "rice ikaw ba yan", "rice kaw ba yan", "ikaw ba yan @ricecooker", "si rice ba yun", "si @ricecooker ba yun", "si rice ba un", "si @ricecooker ba un", "is that @ricecooker"]
angerygreet = ["Shooo", "...", "Wag ka na", ":|"]
athensgreet =["athens", "ganda ako", "ganda ko", "cute ako", "cute me", "cute kasi ako", "cute ko", "cute talaga ako","maganda talaga ako", "maganda kasi ako", "im beautiful", "i am beautiful", "i'm beautiful"]
stressgreet = ["stress", "stresss", "stressss", "stressed", "stressssss", "overstress", "megastress"]
blessgreet = ["bless", "blesss", "blessed"]
drunkgreet = ["lasing"]
atomgreet = ["atom", "nambabakod"]
parrotgreet = ["party parrot", "partyparrot"]
tikigreet = ["meaty", "thicc", "thick", "tiki"]
ferdzgreet = ["happy", "genie"]
jakegreet = ["happy", "joyful"]
justgreet = ["hi", "hello", "henlo", "hallu", "elo", "hellu", "haller", "haler"]
leigreetphrase = ["cute ako", "maganda ako", "pinaka cute", "pinaka maganda", "i am beautiful", "sexy ako", "most beautiful", "ganda ko", "5'11", "qt ko", "qt ako"]
leigreetword = ["pinakacute", "cute", "pinakamaganda"]
revillagreet = ["bong", "revilla", "budots"]
weebgreet = ["anime was a mistake", "weeb shit", "fucking weeb", "fuckin weeb", "fucking weeaboo", "fuckin weeaboo", "damn weeb", "damn weeaboo", "weeb trash", "otaku garbage", "otaku shit", "weaaboo trash", "basura anime", "anime is trash"]
gadongreet = ["mga bobo", "putangina bobo", "puta bobo", "lahat bobo", "kingina bobo"]
saveupgreet = ["budol", "retail therapy"]

leisticker = ["CAADBQADIQEAAiO4mBCSjVKUWk7MNwI", "CAADBQADHAEAAiO4mBCeaC0LYAlkowI", "CAADBQADIAEAAiO4mBD3UdIBPEO6WwI", "CAADBQADGwEAAiO4mBC51PR572t9EgI", "CAADBQADHwEAAiO4mBBJWiwq_cjWdQI", "CAADBQADHgEAAiO4mBBMQuYcpcSX2AI"]
leigif = ["CgADBQADEQADNNrpV_JyDVwU2d1rAg", "CgADBQADFQADDHrhVeaTS0bvbyRWAg", "CgADBQADEAADS754Vha1dmKytEvNAg", "CgADBQADHwADYlzxVfOzb9cCUkuqAg", "CgACAgUAAx0CSte9MwAClZNejvehZnp7f2b00c9IDRE80nM-lwACTwADl_rpVHEOdRWaq2VsGAQ"]
stressgif = ["CgADBQADeAADXqhQVCksGu6IfbQMAg", "CgADBQADMQADSQ5QVUn-yBLRrDvBAg", "CgADBQADagADIQNZVdJEKrwDU24lAg", "CgADBQADNgAD1k_RVFSZibSpxmu4Ag", "CgADBQADFgADjGnIVUDk7DZAN-6XAg", "CgADBQADAwADXbeJVIa-vUgkTDSCAg", "CgACAgUAAx0CSte9MwABARGLX1keJEgTYfvp_x_-TUTSikcTxYIAAiQBAAIOq5BVXaAbYCqk3OUbBA"]
blessgif =["CgADBQADQwADUt_RVJbf7QgSjFMQAg"]
genieferdzgif = "CgADBQADEgADUT_BVqvCsq_FYDT-Ag"
revillagif = "CgADBQADTwADEFuoVswNZyd8icIdAg"
unpluggif = "CgADBQADNwADtjzaDXzFsIuaINkHAg"
landigif = ["CgADBQADHQAD6QuQV_mxPdwxj0s2Ag", "CgADBQADKQADvG2JVi4mEJDnylDvAg"]
louisegif = ["CgADBQADHAADVMqxV2iqwCWWKYXRAg", "CgADBQADRQADggs5VTtpVvYfIcqBAg", "CgADBQADGwADwI9BVYEBhY4qglXKAg", "CgADBQADWwADfhjQVy2VyBHiS3kWAg", "CgADBQADXQADlN5hVIkXruw21LEsAg"]
toastiesgif = ["CgADBQADLwADv4dBVFVtZJ9jdSwFAg"]
nicegif = ["CgACAgUAAx0CSte9MwABARGLX1keJEgTYfvp_x_-TUTSikcTxYIAAiQBAAIOq5BVXaAbYCqk3OUbBA"]
jakegif = ["CgADBQADBwADGIgpVpF8EgH6Mc-9Ag", "CgADBQADCgADuNkwVpThek7KAmXsAg"]
drunkpic = ["AgADBQADOagxGxB_aVZNfo9wNUvyYvGl1jIABMOR93PzURnicEMDAAEC", "AgADBQADOqgxGxB_aVav5vKmhLduCGqk1jIABOQDiHpGpExCJUMDAAEC", "AgADBQADkagxG6Oe8FbPeySNTsva1S5U2zIABHbiq4wGrTTHhxABAAEC", "AgADBQADYKgxGzx76FYspQoUVI_orGFh2zIABPdENNUjOZ6HMQoBAAEC", "AgADBQADyagxG3vgQFfzWyPyZwABhDpToNYyAARIZLO6JHE6rwHyAwABAg", "AgADBQADyqgxG3vgQFdnwo6v0N37ltKu1jIABImnO1LEv_hLsvgDAAEC", "AgADBQADy6gxG3vgQFdhN5CqLNBoaZps3jIABIzvbj8OdXrYa0EAAgI", "AgADBQADzKgxG3vgQFd0wYPinyYN3Zhq2zIABNpbg4ad52tcN0oBAAEC"]
parrotgif = ["CgACAgUAAx0CSte9MwACrcdesncm4JIXcBVtaTvp0ID9BSGHKQACDQEAApeEkFX9mSfmX7NGGBkE", "CgADBAAD0AAEC6xR4O2sp_q6miMC", "CgADBQADbwADJAExVcp6mddA-OvtAg", "CgADBQADLQADkxKZVrE-Wx30uXiNAg", "CgADBQADWAADeL-YVnw3sjCV8aeLAg", "CgADBQADMAADkxKZVp3RsGgriq4TAg", "CgADBQADWQADeL-YVsV0J7Zx1H3-Ag", "CgADBQADLwADamEJVwABfmqsGruuIAI", "CgADBQADRQADxKcIVnp4XIZkwZhFAg", "CgADBQADRgADxKcIVtBU7hnUu1vtAg", "CgADBQADSgADFBMRVvS30XYL8EfxAg", "CgADBQADTQADxKcQVqmmDa3r6kUvAg", "CgADBQADpwADFEmAVV6NgEC76c5qAg", "CgACAgUAAx0CSte9MwABARHrX3R-7kQ9Gg5daA8w-2oRlJbA66AAAoIBAALWKZlXtxMO0RPUg4AbBA", "CgACAgUAAx0CSte9MwABARIiX4aHzWlrh-TzbsqjGlwli-AP6MkAAtUAAw2CMVT9qpSV3tibUxsE", "CgACAgQAAx0CSte9MwABASUlX_0YfxG2gpleK6e26EQbEX3dzi0AAh1eAQABURdkBxxZljmVwNwyHgQ", "CgACAgUAAx0CSte9MwABATHjYCTPvTWxWntHsjWLtso1NEgkv5kAAtUAAw2CMVT9qpSV3tibUx4E", "CgACAgEAAx0CSte9MwABATHmYCTP0sIXzAFK8WEAAbGJpeigAjgaAAKnAAN4ufFHyBWn5lE4ru4eBA", "CgACAgUAAx0CSte9MwABATLlYCnclrET6QVbhRbqYGp-sYFRK0EAAlUBAAK6J1FVIKDpmnmQAAGuHgQ"]
ftwentygif = ["CgADBQADZwADC8sAAVdyPHOcrabSlAI", "CgADBQADBQADilkQVlcE7H79KrlZAg", "CgADBQADNgADZj7JVEzPU_TiD4UHFgQ"]
flandersgif = ["CgADBAADOQADvho0UUaTNwGy6fWJAg"]
weebgif = ["CgADBQADOwADyE_wVe3mk7g8DJnwAg", "CgADBQADWAAD5XgIVd4wMCz9ESrCAg", "CgACAgQAAx0CSte9MwACuXRewo7RKtn4izrnK-R6LgPiwfBpbgACUwADcIS9USzOaoOEG5UYGQQ", "CgACAgQAAx0CSte9MwACuXdewo8I4XLN90FkNNwWVlRoOyPezQACSAIAAvIdHVKmAl4sR-9nsxkE"]
prayerpic = "AgADBQADbagxG4ocsVfyRzCWKWz83cBQ9jIABFnbxMn-gKxBdGgBAAEC"
morningpic = "AgADBQADRKgxG_aNeFXkzaKcraJiFdOA3zIABKp6ugP3u2PoJjgBAAEC"
cebweedgif = ["CgADBQADNgADZj7JVEzPU_TiD4UHAg", "CgACAgQAAx0CSte9MwABAUbiYH6pRokMTbj3mBrwyIz6lVKc7cwAAlkCAAJB7Z1S7GZzwKPLVkcfBA", "CgACAgQAAx0CSte9MwABAUbjYH6pRgpQfm-92ii2tV3gTHvJo-wAAkECAALNBlRRygq8cKZ0q10fBA", "CgACAgQAAx0CSte9MwABAUbkYH6pRuxS8L5FiLEq31OwgWUQDuEAAhwCAAK5-Y1SSIsRTAMEx5AfBA","CgACAgQAAx0CSte9MwABAUblYH6pRmuVgxTnRYGRrE-JHNMa7QoAAicCAALUpI1SuBmAOLB_qGcfBA"]
weedvid = ["https://www.youtube.com/watch?v=sifVwz5Nguc", "https://www.youtube.com/watch?v=DJfg39WkMvE", "https://www.youtube.com/watch?v=iPXKfGxeHIY", "https://www.youtube.com/watch?v=rnS-05XoXs4"]
weedjesusgif = "CgADBQADNgADZj7JVEzPU_TiD4UHAg"
wednesdayfrogpic = "AgADBQADo6gxGzozUFTufJLeTUQaGBt0-TIABAEAAwIAA3gAAwIrBAABFgQ"
gadongif = ["CgACAgUAAx0CSte9MwAC47Fe9rWpOOYFduhDInja8uv7Tu3qdAACkQADaLyhVH1Y2JTFsAvfGgQ", "CgACAgUAAx0CSte9MwAC47Ze9rbtdkufvqc_9crhPm3HUk-d8QACAgEAArquuFeMMB6Stv9IZhoE"]
saveuppic = "AgACAgIAAx0CSte9MwABAUw9YIvpexpB1phsA50lFjIWB-F-FwADMLMxG9ddWUhz53gMnnAPLiC9h6IuAAMBAAMCAAN5AAMfqAEAAR8E"